### ISSUE TITLE
Web version of COIL on broadinstitute.org 504 Gateway Timeout

### ISSUE THREAD

**Issue by xgao32** [kgalinsky/COIL#2]
I tried submitting a 500kb text file with the option of estimating MAF directly from SNP barcode data and kept getting the following
![image](https://user-images.githubusercontent.com/6380557/40192387-2f9aa750-59d2-11e8-94d3-d6fae46d0def.png)

Please advise on how best to proceed with this [text file](https://drive.google.com/file/d/1timTFNOG-vvJih0DauErUlO4jyob2yPU/view) . Thanks

**Comment by kgalinsky** [comment]
You've already submitted this but to the proper repository (https://github.com/Greenhouse-Lab/THEREALMcCOIL/issues/5). You can try installing the version of COIL here and running it, but I haven't touched this code in ages and will not be able to provide any support.
